### ISSUE TITLE
Merge intersecting holes (two-dimensional case)

### ISSUE THREAD

**Issue by Priusds** [Priusds/Bubbles#29]
For now, adding new holes to a `Topology` object is only possible as long they are not intersecting old ones.
Do we want to lose this?

- [ ] List all annoying edge cases.
- [ ] How to parametrize non-stellar holes?

**Comment by Drachiro** [comment]
With the new topology class holes can now merge. If the holes have same level they will  be merged if no collision constraints are given. If holes have different level and no collision constraints, they will be merged at plot or meshing level (e.g. via gmsh)
