### ISSUE TITLE
Transform Framework

### ISSUE THREAD

**Issue by Priusds** [Priusds/Bubbles#46]

**Comment by Drachiro** [comment]
Introduce the transform framework, that will be used in the add mechanics in the topology class. 

For this provide simple transforms : 

Transforms to treat periodic boundary cases :  (including possible merging)
- [ ] Period in x direction only (width depency)
- [ ] Periodic in y direction      (height dependency)
- [ ] Perdiodic X Y behavior (concatenation of x and y) 

General transforms: 

- [ ] Rotations
- [ ] Affine mappings
- [ ] Diffeomorphism (function interface)

**Comment by Drachiro** [comment]
Class Periodic now involves all Periodic X,Y, XY in a single concepts. 

Class Diffeomorphism involves Rotation, Affine mappings.
